// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArEz42HwILh0iqDeyO3UnLPWrF8rEwuck',
    appId: '1:644169354163:web:3d31739d3f3587b07519c6',
    messagingSenderId: '644169354163',
    projectId: 'mobile-notebook-project',
    authDomain: 'mobile-notebook-project.firebaseapp.com',
    storageBucket: 'mobile-notebook-project.appspot.com',
    measurementId: 'G-0HZGC72Y0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzIUSalHxHMBMrCoNh8j1Zkah06385E_s',
    appId: '1:644169354163:android:1816e1a834186df27519c6',
    messagingSenderId: '644169354163',
    projectId: 'mobile-notebook-project',
    storageBucket: 'mobile-notebook-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcf1_si3WcCYocBbjSBa9aav3JZUoUWk',
    appId: '1:644169354163:ios:8ec3cfe18b640bc37519c6',
    messagingSenderId: '644169354163',
    projectId: 'mobile-notebook-project',
    storageBucket: 'mobile-notebook-project.appspot.com',
    iosClientId: '644169354163-olfs3a2mogt9vrbm6t0dj6n7rfd74vul.apps.googleusercontent.com',
    iosBundleId: 'com.ifeanyichukwu',
  );
}
